[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "*"
[[redirects]]
  from = "/api"
  to = "https://287d-95-70-156-196.eu.ngrok.io/api"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}
